name: infrastructure
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - baxter-net
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    restart:  unless-stopped
    hostname: kafka
    depends_on:
      - zookeeper
    networks:
      - baxter-net
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 15s

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    restart: on-failure
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - baxter-net
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
          echo "Kafka is healthy! Creating topics...";
          kafka-topics --bootstrap-server kafka:9092 --create \
          --topic AccountRegistered --if-not-exists \
          --partitions 1 --replication-factor 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - baxter-net
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: baxter-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

networks:
  baxter-net:
    name: "baxter-net"
    driver: bridge
